from tkinter import *
root = Tk()
username = Label(root,text = "username").grid(row = 0, column = 0)
e1 = Entry(root).grid(row = 0, column = 1)
password = Label(root,text = "Password").grid(row = 1, column = 0)
e2 = Entry(root).grid(row = 1, column = 1)
email = Label(root,text = "email").grid(row = 2, column = 0)
e3 = Entry(root).grid(row = 2, column = 1)
age = Label(root,text = "age").grid(row = 3, column = 0)
e4 = Entry(root).grid(row = 3, column = 1)
contact_no = Label(root,text = "contact_no").grid(row = 4, column = 0)
e5 = Entry(root).grid(row = 4, column = 1)
submit = Button(root, text = "Submit").grid(row = 6, column = 2)
root.mainloop()